CREATE DATABASE kratos;
CREATE DATABASE hydra;

CREATE USER kratos WITH PASSWORD 'secret';
CREATE USER hydra WITH PASSWORD 'secret';

GRANT ALL PRIVILEGES ON DATABASE kratos TO kratos;
GRANT ALL PRIVILEGES ON DATABASE hydra TO hydra;

ALTER DATABASE kratos OWNER TO kratos;
ALTER DATABASE hydra OWNER TO hydra;