services:
  # Ory Hydra
  hydra-migrate:
    container_name: hydra-migrate
    image: oryd/hydra:latest
    depends_on:
      - postgres
    command: migrate sql -e --yes
    environment:
      - DSN=postgres://ory:secret@postgres:5432/hydra?sslmode=disable

  hydra:
    ports:
      - "4444:4444" # Public API
      - "4445:4445" # Admin API
    container_name: hydra
    image: oryd/hydra:latest
    depends_on:
      - hydra-migrate
      - postgres
    command: serve all --dev --config /etc/config/hydra/hydra.yml
    volumes:
      - ../../../services/authorization/config:/etc/config/hydra
